/**
 * Generate sitemap.xml for production.
 *
 * Reads static pages from dist/client/pages.json, then writes dist/client/sitemap.xml.
 *
 * Usage:
 *   node apps/web/scripts/generate-sitemap.mjs
 *
 * Env vars (optional, fall back to defaults):
 *   PUBLIC_BASE_URL   — canonical site origin, e.g. https://megick.com
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const webRoot = resolve(__dirname, "..");
const repoRoot = resolve(webRoot, "../..");
const apiRoot = resolve(webRoot, "../api");
const clientDist = resolve(webRoot, "dist/client");

loadEnvFiles([repoRoot, apiRoot, webRoot], process.env.APP_ENV || process.env.NODE_ENV || "production");

// ── Config ─────────────────────────────────────────────────────────────────

const siteUrl = (process.env.PUBLIC_BASE_URL ?? "https://megick.com").replace(/\/+$/, "");
const outputPath = resolve(clientDist, "sitemap.xml");
const pagesJsonPath = resolve(clientDist, "pages.json");

const EXCLUDED_STATIC_SITEMAP_PATHS = new Set([
  // /generate immediately redirects users into the authenticated app and advertises noindex.
  "/generate",
]);

// ── Helpers ─────────────────────────────────────────────────────────────────

function today() {
  return new Date().toISOString().slice(0, 10);
}

function loadEnvFiles(roots, mode) {
  const shellEnv = new Set(Object.keys(process.env));
  const fileNames = [".env", ".env.local", `.env.${mode}`, `.env.${mode}.local`];

  for (const root of roots) {
    for (const fileName of fileNames) {
      const filePath = resolve(root, fileName);
      if (!existsSync(filePath)) continue;
      const entries = parseEnvFile(readFileSync(filePath, "utf-8"));
      for (const [key, value] of Object.entries(entries)) {
        if (!shellEnv.has(key)) process.env[key] = value;
      }
    }
  }
}

function parseEnvFile(content) {
  const entries = {};
  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;

    const match = line.match(/^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/);
    if (!match) continue;

    let value = match[2].trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    } else {
      const commentIndex = value.search(/\s#/);
      if (commentIndex >= 0) value = value.slice(0, commentIndex).trim();
    }

    entries[match[1]] = value;
  }
  return entries;
}

function escapeXml(value) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function canonicalPath(path) {
  return new URL(path, "https://megick.local").pathname;
}

function canonicalUrl(path) {
  return new URL(path, `${siteUrl}/`).toString();
}

function buildUrl(path, { priority, changefreq }) {
  return [
    "  <url>",
    `    <loc>${escapeXml(canonicalUrl(path))}</loc>`,
    `    <lastmod>${today()}</lastmod>`,
    `    <priority>${priority}</priority>`,
    `    <changefreq>${changefreq}</changefreq>`,
    "  </url>",
  ].join("\n");
}

// ── Load static pages ────────────────────────────────────────────────────────

if (!existsSync(pagesJsonPath)) {
  console.error(`pages.json not found at ${pagesJsonPath}`);
  console.error("Run `pnpm build:web` first.");
  process.exit(1);
}

const { pages: staticPages } = JSON.parse(readFileSync(pagesJsonPath, "utf-8"));

// ── Build URL entries ────────────────────────────────────────────────────────

const staticEntries = staticPages
  .filter((page) => !EXCLUDED_STATIC_SITEMAP_PATHS.has(canonicalPath(page.path)))
  .map((page) => buildUrl(page.path, page.sitemap));

const allEntries = staticEntries;

// ── Write sitemap ────────────────────────────────────────────────────────────

const xml = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<urlset xmlns="https://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">',
  "  <!--Generated by scripts/generate-sitemap.mjs-->",
  ...allEntries,
  "</urlset>",
  "",
].join("\n");

writeFileSync(outputPath, xml, "utf-8");
console.log(`Wrote ${allEntries.length} URL(s) to ${outputPath}`);
