/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OfficialRouteImport } from './routes/official'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as DesktopLoginRouteImport } from './routes/desktop-login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as EditorSessionIdRouteImport } from './routes/editor.$sessionId'
import { Route as DashboardVideoEditorRouteImport } from './routes/dashboard.video-editor'
import { Route as DashboardTemplatesRouteImport } from './routes/dashboard.templates'
import { Route as DashboardTemplateRouteImport } from './routes/dashboard.template'
import { Route as DashboardStudioRouteImport } from './routes/dashboard.studio'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardOverviewRouteImport } from './routes/dashboard.overview'
import { Route as DashboardMediaCenterRouteImport } from './routes/dashboard.media-center'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as DashboardChatsRouteImport } from './routes/dashboard.chats'
import { Route as AdminVideoTemplatesRouteImport } from './routes/admin.video-templates'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminUserChatsRouteImport } from './routes/admin.user-chats'
import { Route as AdminTemplateCategoriesRouteImport } from './routes/admin.template-categories'
import { Route as AdminSiteSettingsRouteImport } from './routes/admin.site-settings'
import { Route as AdminShowcaseRouteImport } from './routes/admin.showcase'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminQueuesRouteImport } from './routes/admin.queues'
import { Route as AdminOauthProvidersRouteImport } from './routes/admin.oauth-providers'
import { Route as AdminNavigationMenusRouteImport } from './routes/admin.navigation-menus'
import { Route as AdminModelProvidersRouteImport } from './routes/admin.model-providers'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminImageTemplatesRouteImport } from './routes/admin.image-templates'
import { Route as AdminGenerationJobsRouteImport } from './routes/admin.generation-jobs'
import { Route as AdminDesktopUpdatesRouteImport } from './routes/admin.desktop-updates'
import { Route as AdminAuditLogRouteImport } from './routes/admin.audit-log'
import { Route as AdminAiModelsRouteImport } from './routes/admin.ai-models'
import { Route as AdminAiImageEditModesRouteImport } from './routes/admin.ai-image-edit-modes'
import { Route as DashboardTemplatesIndexRouteImport } from './routes/dashboard.templates.index'
import { Route as DashboardTemplateIndexRouteImport } from './routes/dashboard.template.index'
import { Route as DashboardTemplatesTemplateIdRouteImport } from './routes/dashboard.templates.$templateId'
import { Route as DashboardTemplateTemplateIdRouteImport } from './routes/dashboard.template.$templateId'
import { Route as DashboardStudioVideoRouteImport } from './routes/dashboard.studio.video'
import { Route as DashboardStudioImageRouteImport } from './routes/dashboard.studio.image'
import { Route as DashboardJobsJobIdRouteImport } from './routes/dashboard.jobs.$jobId'
import { Route as AdminCloudResourcesR2RouteImport } from './routes/admin.cloud-resources.r2'
import { Route as AdminCloudResourcesOssRouteImport } from './routes/admin.cloud-resources.oss'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficialRoute = OfficialRouteImport.update({
  id: '/official',
  path: '/official',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const DesktopLoginRoute = DesktopLoginRouteImport.update({
  id: '/desktop-login',
  path: '/desktop-login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TemplatesRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const EditorSessionIdRoute = EditorSessionIdRouteImport.update({
  id: '/editor/$sessionId',
  path: '/editor/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVideoEditorRoute = DashboardVideoEditorRouteImport.update({
  id: '/video-editor',
  path: '/video-editor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTemplatesRoute = DashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTemplateRoute = DashboardTemplateRouteImport.update({
  id: '/template',
  path: '/template',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudioRoute = DashboardStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMediaCenterRoute = DashboardMediaCenterRouteImport.update({
  id: '/media-center',
  path: '/media-center',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatsRoute = DashboardChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminVideoTemplatesRoute = AdminVideoTemplatesRouteImport.update({
  id: '/video-templates',
  path: '/video-templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUserChatsRoute = AdminUserChatsRouteImport.update({
  id: '/user-chats',
  path: '/user-chats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplateCategoriesRoute = AdminTemplateCategoriesRouteImport.update({
  id: '/template-categories',
  path: '/template-categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteSettingsRoute = AdminSiteSettingsRouteImport.update({
  id: '/site-settings',
  path: '/site-settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShowcaseRoute = AdminShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQueuesRoute = AdminQueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOauthProvidersRoute = AdminOauthProvidersRouteImport.update({
  id: '/oauth-providers',
  path: '/oauth-providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNavigationMenusRoute = AdminNavigationMenusRouteImport.update({
  id: '/navigation-menus',
  path: '/navigation-menus',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModelProvidersRoute = AdminModelProvidersRouteImport.update({
  id: '/model-providers',
  path: '/model-providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImageTemplatesRoute = AdminImageTemplatesRouteImport.update({
  id: '/image-templates',
  path: '/image-templates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGenerationJobsRoute = AdminGenerationJobsRouteImport.update({
  id: '/generation-jobs',
  path: '/generation-jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDesktopUpdatesRoute = AdminDesktopUpdatesRouteImport.update({
  id: '/desktop-updates',
  path: '/desktop-updates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiModelsRoute = AdminAiModelsRouteImport.update({
  id: '/ai-models',
  path: '/ai-models',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiImageEditModesRoute = AdminAiImageEditModesRouteImport.update({
  id: '/ai-image-edit-modes',
  path: '/ai-image-edit-modes',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardTemplatesIndexRoute = DashboardTemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardTemplatesRoute,
} as any)
const DashboardTemplateIndexRoute = DashboardTemplateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardTemplateRoute,
} as any)
const DashboardTemplatesTemplateIdRoute =
  DashboardTemplatesTemplateIdRouteImport.update({
    id: '/$templateId',
    path: '/$templateId',
    getParentRoute: () => DashboardTemplatesRoute,
  } as any)
const DashboardTemplateTemplateIdRoute =
  DashboardTemplateTemplateIdRouteImport.update({
    id: '/$templateId',
    path: '/$templateId',
    getParentRoute: () => DashboardTemplateRoute,
  } as any)
const DashboardStudioVideoRoute = DashboardStudioVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => DashboardStudioRoute,
} as any)
const DashboardStudioImageRoute = DashboardStudioImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => DashboardStudioRoute,
} as any)
const DashboardJobsJobIdRoute = DashboardJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminCloudResourcesR2Route = AdminCloudResourcesR2RouteImport.update({
  id: '/cloud-resources/r2',
  path: '/cloud-resources/r2',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCloudResourcesOssRoute = AdminCloudResourcesOssRouteImport.update({
  id: '/cloud-resources/oss',
  path: '/cloud-resources/oss',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/desktop-login': typeof DesktopLoginRoute
  '/generate': typeof GenerateRoute
  '/login': typeof LoginRoute
  '/official': typeof OfficialRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/ai-image-edit-modes': typeof AdminAiImageEditModesRoute
  '/admin/ai-models': typeof AdminAiModelsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/desktop-updates': typeof AdminDesktopUpdatesRoute
  '/admin/generation-jobs': typeof AdminGenerationJobsRoute
  '/admin/image-templates': typeof AdminImageTemplatesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/model-providers': typeof AdminModelProvidersRoute
  '/admin/navigation-menus': typeof AdminNavigationMenusRoute
  '/admin/oauth-providers': typeof AdminOauthProvidersRoute
  '/admin/queues': typeof AdminQueuesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/showcase': typeof AdminShowcaseRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/template-categories': typeof AdminTemplateCategoriesRoute
  '/admin/user-chats': typeof AdminUserChatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/video-templates': typeof AdminVideoTemplatesRoute
  '/dashboard/chats': typeof DashboardChatsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/media-center': typeof DashboardMediaCenterRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/studio': typeof DashboardStudioRouteWithChildren
  '/dashboard/template': typeof DashboardTemplateRouteWithChildren
  '/dashboard/templates': typeof DashboardTemplatesRouteWithChildren
  '/dashboard/video-editor': typeof DashboardVideoEditorRoute
  '/editor/$sessionId': typeof EditorSessionIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/admin/cloud-resources/oss': typeof AdminCloudResourcesOssRoute
  '/admin/cloud-resources/r2': typeof AdminCloudResourcesR2Route
  '/dashboard/jobs/$jobId': typeof DashboardJobsJobIdRoute
  '/dashboard/studio/image': typeof DashboardStudioImageRoute
  '/dashboard/studio/video': typeof DashboardStudioVideoRoute
  '/dashboard/template/$templateId': typeof DashboardTemplateTemplateIdRoute
  '/dashboard/templates/$templateId': typeof DashboardTemplatesTemplateIdRoute
  '/dashboard/template/': typeof DashboardTemplateIndexRoute
  '/dashboard/templates/': typeof DashboardTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/desktop-login': typeof DesktopLoginRoute
  '/generate': typeof GenerateRoute
  '/login': typeof LoginRoute
  '/official': typeof OfficialRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/admin/ai-image-edit-modes': typeof AdminAiImageEditModesRoute
  '/admin/ai-models': typeof AdminAiModelsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/desktop-updates': typeof AdminDesktopUpdatesRoute
  '/admin/generation-jobs': typeof AdminGenerationJobsRoute
  '/admin/image-templates': typeof AdminImageTemplatesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/model-providers': typeof AdminModelProvidersRoute
  '/admin/navigation-menus': typeof AdminNavigationMenusRoute
  '/admin/oauth-providers': typeof AdminOauthProvidersRoute
  '/admin/queues': typeof AdminQueuesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/showcase': typeof AdminShowcaseRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/template-categories': typeof AdminTemplateCategoriesRoute
  '/admin/user-chats': typeof AdminUserChatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/video-templates': typeof AdminVideoTemplatesRoute
  '/dashboard/chats': typeof DashboardChatsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/media-center': typeof DashboardMediaCenterRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/studio': typeof DashboardStudioRouteWithChildren
  '/dashboard/video-editor': typeof DashboardVideoEditorRoute
  '/editor/$sessionId': typeof EditorSessionIdRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/admin/cloud-resources/oss': typeof AdminCloudResourcesOssRoute
  '/admin/cloud-resources/r2': typeof AdminCloudResourcesR2Route
  '/dashboard/jobs/$jobId': typeof DashboardJobsJobIdRoute
  '/dashboard/studio/image': typeof DashboardStudioImageRoute
  '/dashboard/studio/video': typeof DashboardStudioVideoRoute
  '/dashboard/template/$templateId': typeof DashboardTemplateTemplateIdRoute
  '/dashboard/templates/$templateId': typeof DashboardTemplatesTemplateIdRoute
  '/dashboard/template': typeof DashboardTemplateIndexRoute
  '/dashboard/templates': typeof DashboardTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/desktop-login': typeof DesktopLoginRoute
  '/generate': typeof GenerateRoute
  '/login': typeof LoginRoute
  '/official': typeof OfficialRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/ai-image-edit-modes': typeof AdminAiImageEditModesRoute
  '/admin/ai-models': typeof AdminAiModelsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/desktop-updates': typeof AdminDesktopUpdatesRoute
  '/admin/generation-jobs': typeof AdminGenerationJobsRoute
  '/admin/image-templates': typeof AdminImageTemplatesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/model-providers': typeof AdminModelProvidersRoute
  '/admin/navigation-menus': typeof AdminNavigationMenusRoute
  '/admin/oauth-providers': typeof AdminOauthProvidersRoute
  '/admin/queues': typeof AdminQueuesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/showcase': typeof AdminShowcaseRoute
  '/admin/site-settings': typeof AdminSiteSettingsRoute
  '/admin/template-categories': typeof AdminTemplateCategoriesRoute
  '/admin/user-chats': typeof AdminUserChatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/video-templates': typeof AdminVideoTemplatesRoute
  '/dashboard/chats': typeof DashboardChatsRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/media-center': typeof DashboardMediaCenterRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/studio': typeof DashboardStudioRouteWithChildren
  '/dashboard/template': typeof DashboardTemplateRouteWithChildren
  '/dashboard/templates': typeof DashboardTemplatesRouteWithChildren
  '/dashboard/video-editor': typeof DashboardVideoEditorRoute
  '/editor/$sessionId': typeof EditorSessionIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/admin/cloud-resources/oss': typeof AdminCloudResourcesOssRoute
  '/admin/cloud-resources/r2': typeof AdminCloudResourcesR2Route
  '/dashboard/jobs/$jobId': typeof DashboardJobsJobIdRoute
  '/dashboard/studio/image': typeof DashboardStudioImageRoute
  '/dashboard/studio/video': typeof DashboardStudioVideoRoute
  '/dashboard/template/$templateId': typeof DashboardTemplateTemplateIdRoute
  '/dashboard/templates/$templateId': typeof DashboardTemplatesTemplateIdRoute
  '/dashboard/template/': typeof DashboardTemplateIndexRoute
  '/dashboard/templates/': typeof DashboardTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/desktop-login'
    | '/generate'
    | '/login'
    | '/official'
    | '/privacy'
    | '/signup'
    | '/templates'
    | '/terms'
    | '/admin/ai-image-edit-modes'
    | '/admin/ai-models'
    | '/admin/audit-log'
    | '/admin/desktop-updates'
    | '/admin/generation-jobs'
    | '/admin/image-templates'
    | '/admin/login'
    | '/admin/model-providers'
    | '/admin/navigation-menus'
    | '/admin/oauth-providers'
    | '/admin/queues'
    | '/admin/roles'
    | '/admin/showcase'
    | '/admin/site-settings'
    | '/admin/template-categories'
    | '/admin/user-chats'
    | '/admin/users'
    | '/admin/video-templates'
    | '/dashboard/chats'
    | '/dashboard/history'
    | '/dashboard/media-center'
    | '/dashboard/overview'
    | '/dashboard/profile'
    | '/dashboard/studio'
    | '/dashboard/template'
    | '/dashboard/templates'
    | '/dashboard/video-editor'
    | '/editor/$sessionId'
    | '/admin/'
    | '/dashboard/'
    | '/templates/'
    | '/admin/cloud-resources/oss'
    | '/admin/cloud-resources/r2'
    | '/dashboard/jobs/$jobId'
    | '/dashboard/studio/image'
    | '/dashboard/studio/video'
    | '/dashboard/template/$templateId'
    | '/dashboard/templates/$templateId'
    | '/dashboard/template/'
    | '/dashboard/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/desktop-login'
    | '/generate'
    | '/login'
    | '/official'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/admin/ai-image-edit-modes'
    | '/admin/ai-models'
    | '/admin/audit-log'
    | '/admin/desktop-updates'
    | '/admin/generation-jobs'
    | '/admin/image-templates'
    | '/admin/login'
    | '/admin/model-providers'
    | '/admin/navigation-menus'
    | '/admin/oauth-providers'
    | '/admin/queues'
    | '/admin/roles'
    | '/admin/showcase'
    | '/admin/site-settings'
    | '/admin/template-categories'
    | '/admin/user-chats'
    | '/admin/users'
    | '/admin/video-templates'
    | '/dashboard/chats'
    | '/dashboard/history'
    | '/dashboard/media-center'
    | '/dashboard/overview'
    | '/dashboard/profile'
    | '/dashboard/studio'
    | '/dashboard/video-editor'
    | '/editor/$sessionId'
    | '/admin'
    | '/dashboard'
    | '/templates'
    | '/admin/cloud-resources/oss'
    | '/admin/cloud-resources/r2'
    | '/dashboard/jobs/$jobId'
    | '/dashboard/studio/image'
    | '/dashboard/studio/video'
    | '/dashboard/template/$templateId'
    | '/dashboard/templates/$templateId'
    | '/dashboard/template'
    | '/dashboard/templates'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/desktop-login'
    | '/generate'
    | '/login'
    | '/official'
    | '/privacy'
    | '/signup'
    | '/templates'
    | '/terms'
    | '/admin/ai-image-edit-modes'
    | '/admin/ai-models'
    | '/admin/audit-log'
    | '/admin/desktop-updates'
    | '/admin/generation-jobs'
    | '/admin/image-templates'
    | '/admin/login'
    | '/admin/model-providers'
    | '/admin/navigation-menus'
    | '/admin/oauth-providers'
    | '/admin/queues'
    | '/admin/roles'
    | '/admin/showcase'
    | '/admin/site-settings'
    | '/admin/template-categories'
    | '/admin/user-chats'
    | '/admin/users'
    | '/admin/video-templates'
    | '/dashboard/chats'
    | '/dashboard/history'
    | '/dashboard/media-center'
    | '/dashboard/overview'
    | '/dashboard/profile'
    | '/dashboard/studio'
    | '/dashboard/template'
    | '/dashboard/templates'
    | '/dashboard/video-editor'
    | '/editor/$sessionId'
    | '/admin/'
    | '/dashboard/'
    | '/templates/'
    | '/admin/cloud-resources/oss'
    | '/admin/cloud-resources/r2'
    | '/dashboard/jobs/$jobId'
    | '/dashboard/studio/image'
    | '/dashboard/studio/video'
    | '/dashboard/template/$templateId'
    | '/dashboard/templates/$templateId'
    | '/dashboard/template/'
    | '/dashboard/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  DesktopLoginRoute: typeof DesktopLoginRoute
  GenerateRoute: typeof GenerateRoute
  LoginRoute: typeof LoginRoute
  OfficialRoute: typeof OfficialRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
  TermsRoute: typeof TermsRoute
  EditorSessionIdRoute: typeof EditorSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/official': {
      id: '/official'
      path: '/official'
      fullPath: '/official'
      preLoaderRoute: typeof OfficialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desktop-login': {
      id: '/desktop-login'
      path: '/desktop-login'
      fullPath: '/desktop-login'
      preLoaderRoute: typeof DesktopLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/editor/$sessionId': {
      id: '/editor/$sessionId'
      path: '/editor/$sessionId'
      fullPath: '/editor/$sessionId'
      preLoaderRoute: typeof EditorSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/video-editor': {
      id: '/dashboard/video-editor'
      path: '/video-editor'
      fullPath: '/dashboard/video-editor'
      preLoaderRoute: typeof DashboardVideoEditorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/templates': {
      id: '/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/template': {
      id: '/dashboard/template'
      path: '/template'
      fullPath: '/dashboard/template'
      preLoaderRoute: typeof DashboardTemplateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/studio': {
      id: '/dashboard/studio'
      path: '/studio'
      fullPath: '/dashboard/studio'
      preLoaderRoute: typeof DashboardStudioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/overview': {
      id: '/dashboard/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/media-center': {
      id: '/dashboard/media-center'
      path: '/media-center'
      fullPath: '/dashboard/media-center'
      preLoaderRoute: typeof DashboardMediaCenterRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chats': {
      id: '/dashboard/chats'
      path: '/chats'
      fullPath: '/dashboard/chats'
      preLoaderRoute: typeof DashboardChatsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/video-templates': {
      id: '/admin/video-templates'
      path: '/video-templates'
      fullPath: '/admin/video-templates'
      preLoaderRoute: typeof AdminVideoTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/user-chats': {
      id: '/admin/user-chats'
      path: '/user-chats'
      fullPath: '/admin/user-chats'
      preLoaderRoute: typeof AdminUserChatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/template-categories': {
      id: '/admin/template-categories'
      path: '/template-categories'
      fullPath: '/admin/template-categories'
      preLoaderRoute: typeof AdminTemplateCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site-settings': {
      id: '/admin/site-settings'
      path: '/site-settings'
      fullPath: '/admin/site-settings'
      preLoaderRoute: typeof AdminSiteSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/showcase': {
      id: '/admin/showcase'
      path: '/showcase'
      fullPath: '/admin/showcase'
      preLoaderRoute: typeof AdminShowcaseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/queues': {
      id: '/admin/queues'
      path: '/queues'
      fullPath: '/admin/queues'
      preLoaderRoute: typeof AdminQueuesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/oauth-providers': {
      id: '/admin/oauth-providers'
      path: '/oauth-providers'
      fullPath: '/admin/oauth-providers'
      preLoaderRoute: typeof AdminOauthProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/navigation-menus': {
      id: '/admin/navigation-menus'
      path: '/navigation-menus'
      fullPath: '/admin/navigation-menus'
      preLoaderRoute: typeof AdminNavigationMenusRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/model-providers': {
      id: '/admin/model-providers'
      path: '/model-providers'
      fullPath: '/admin/model-providers'
      preLoaderRoute: typeof AdminModelProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/image-templates': {
      id: '/admin/image-templates'
      path: '/image-templates'
      fullPath: '/admin/image-templates'
      preLoaderRoute: typeof AdminImageTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/generation-jobs': {
      id: '/admin/generation-jobs'
      path: '/generation-jobs'
      fullPath: '/admin/generation-jobs'
      preLoaderRoute: typeof AdminGenerationJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/desktop-updates': {
      id: '/admin/desktop-updates'
      path: '/desktop-updates'
      fullPath: '/admin/desktop-updates'
      preLoaderRoute: typeof AdminDesktopUpdatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-models': {
      id: '/admin/ai-models'
      path: '/ai-models'
      fullPath: '/admin/ai-models'
      preLoaderRoute: typeof AdminAiModelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-image-edit-modes': {
      id: '/admin/ai-image-edit-modes'
      path: '/ai-image-edit-modes'
      fullPath: '/admin/ai-image-edit-modes'
      preLoaderRoute: typeof AdminAiImageEditModesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/templates/': {
      id: '/dashboard/templates/'
      path: '/'
      fullPath: '/dashboard/templates/'
      preLoaderRoute: typeof DashboardTemplatesIndexRouteImport
      parentRoute: typeof DashboardTemplatesRoute
    }
    '/dashboard/template/': {
      id: '/dashboard/template/'
      path: '/'
      fullPath: '/dashboard/template/'
      preLoaderRoute: typeof DashboardTemplateIndexRouteImport
      parentRoute: typeof DashboardTemplateRoute
    }
    '/dashboard/templates/$templateId': {
      id: '/dashboard/templates/$templateId'
      path: '/$templateId'
      fullPath: '/dashboard/templates/$templateId'
      preLoaderRoute: typeof DashboardTemplatesTemplateIdRouteImport
      parentRoute: typeof DashboardTemplatesRoute
    }
    '/dashboard/template/$templateId': {
      id: '/dashboard/template/$templateId'
      path: '/$templateId'
      fullPath: '/dashboard/template/$templateId'
      preLoaderRoute: typeof DashboardTemplateTemplateIdRouteImport
      parentRoute: typeof DashboardTemplateRoute
    }
    '/dashboard/studio/video': {
      id: '/dashboard/studio/video'
      path: '/video'
      fullPath: '/dashboard/studio/video'
      preLoaderRoute: typeof DashboardStudioVideoRouteImport
      parentRoute: typeof DashboardStudioRoute
    }
    '/dashboard/studio/image': {
      id: '/dashboard/studio/image'
      path: '/image'
      fullPath: '/dashboard/studio/image'
      preLoaderRoute: typeof DashboardStudioImageRouteImport
      parentRoute: typeof DashboardStudioRoute
    }
    '/dashboard/jobs/$jobId': {
      id: '/dashboard/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/dashboard/jobs/$jobId'
      preLoaderRoute: typeof DashboardJobsJobIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/cloud-resources/r2': {
      id: '/admin/cloud-resources/r2'
      path: '/cloud-resources/r2'
      fullPath: '/admin/cloud-resources/r2'
      preLoaderRoute: typeof AdminCloudResourcesR2RouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cloud-resources/oss': {
      id: '/admin/cloud-resources/oss'
      path: '/cloud-resources/oss'
      fullPath: '/admin/cloud-resources/oss'
      preLoaderRoute: typeof AdminCloudResourcesOssRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAiImageEditModesRoute: typeof AdminAiImageEditModesRoute
  AdminAiModelsRoute: typeof AdminAiModelsRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminDesktopUpdatesRoute: typeof AdminDesktopUpdatesRoute
  AdminGenerationJobsRoute: typeof AdminGenerationJobsRoute
  AdminImageTemplatesRoute: typeof AdminImageTemplatesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminModelProvidersRoute: typeof AdminModelProvidersRoute
  AdminNavigationMenusRoute: typeof AdminNavigationMenusRoute
  AdminOauthProvidersRoute: typeof AdminOauthProvidersRoute
  AdminQueuesRoute: typeof AdminQueuesRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminShowcaseRoute: typeof AdminShowcaseRoute
  AdminSiteSettingsRoute: typeof AdminSiteSettingsRoute
  AdminTemplateCategoriesRoute: typeof AdminTemplateCategoriesRoute
  AdminUserChatsRoute: typeof AdminUserChatsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVideoTemplatesRoute: typeof AdminVideoTemplatesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCloudResourcesOssRoute: typeof AdminCloudResourcesOssRoute
  AdminCloudResourcesR2Route: typeof AdminCloudResourcesR2Route
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiImageEditModesRoute: AdminAiImageEditModesRoute,
  AdminAiModelsRoute: AdminAiModelsRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminDesktopUpdatesRoute: AdminDesktopUpdatesRoute,
  AdminGenerationJobsRoute: AdminGenerationJobsRoute,
  AdminImageTemplatesRoute: AdminImageTemplatesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminModelProvidersRoute: AdminModelProvidersRoute,
  AdminNavigationMenusRoute: AdminNavigationMenusRoute,
  AdminOauthProvidersRoute: AdminOauthProvidersRoute,
  AdminQueuesRoute: AdminQueuesRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminShowcaseRoute: AdminShowcaseRoute,
  AdminSiteSettingsRoute: AdminSiteSettingsRoute,
  AdminTemplateCategoriesRoute: AdminTemplateCategoriesRoute,
  AdminUserChatsRoute: AdminUserChatsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVideoTemplatesRoute: AdminVideoTemplatesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCloudResourcesOssRoute: AdminCloudResourcesOssRoute,
  AdminCloudResourcesR2Route: AdminCloudResourcesR2Route,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardStudioRouteChildren {
  DashboardStudioImageRoute: typeof DashboardStudioImageRoute
  DashboardStudioVideoRoute: typeof DashboardStudioVideoRoute
}

const DashboardStudioRouteChildren: DashboardStudioRouteChildren = {
  DashboardStudioImageRoute: DashboardStudioImageRoute,
  DashboardStudioVideoRoute: DashboardStudioVideoRoute,
}

const DashboardStudioRouteWithChildren = DashboardStudioRoute._addFileChildren(
  DashboardStudioRouteChildren,
)

interface DashboardTemplateRouteChildren {
  DashboardTemplateTemplateIdRoute: typeof DashboardTemplateTemplateIdRoute
  DashboardTemplateIndexRoute: typeof DashboardTemplateIndexRoute
}

const DashboardTemplateRouteChildren: DashboardTemplateRouteChildren = {
  DashboardTemplateTemplateIdRoute: DashboardTemplateTemplateIdRoute,
  DashboardTemplateIndexRoute: DashboardTemplateIndexRoute,
}

const DashboardTemplateRouteWithChildren =
  DashboardTemplateRoute._addFileChildren(DashboardTemplateRouteChildren)

interface DashboardTemplatesRouteChildren {
  DashboardTemplatesTemplateIdRoute: typeof DashboardTemplatesTemplateIdRoute
  DashboardTemplatesIndexRoute: typeof DashboardTemplatesIndexRoute
}

const DashboardTemplatesRouteChildren: DashboardTemplatesRouteChildren = {
  DashboardTemplatesTemplateIdRoute: DashboardTemplatesTemplateIdRoute,
  DashboardTemplatesIndexRoute: DashboardTemplatesIndexRoute,
}

const DashboardTemplatesRouteWithChildren =
  DashboardTemplatesRoute._addFileChildren(DashboardTemplatesRouteChildren)

interface DashboardRouteChildren {
  DashboardChatsRoute: typeof DashboardChatsRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardMediaCenterRoute: typeof DashboardMediaCenterRoute
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardStudioRoute: typeof DashboardStudioRouteWithChildren
  DashboardTemplateRoute: typeof DashboardTemplateRouteWithChildren
  DashboardTemplatesRoute: typeof DashboardTemplatesRouteWithChildren
  DashboardVideoEditorRoute: typeof DashboardVideoEditorRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardJobsJobIdRoute: typeof DashboardJobsJobIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardChatsRoute: DashboardChatsRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardMediaCenterRoute: DashboardMediaCenterRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardStudioRoute: DashboardStudioRouteWithChildren,
  DashboardTemplateRoute: DashboardTemplateRouteWithChildren,
  DashboardTemplatesRoute: DashboardTemplatesRouteWithChildren,
  DashboardVideoEditorRoute: DashboardVideoEditorRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardJobsJobIdRoute: DashboardJobsJobIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface TemplatesRouteChildren {
  TemplatesIndexRoute: typeof TemplatesIndexRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesIndexRoute: TemplatesIndexRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  DesktopLoginRoute: DesktopLoginRoute,
  GenerateRoute: GenerateRoute,
  LoginRoute: LoginRoute,
  OfficialRoute: OfficialRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
  TermsRoute: TermsRoute,
  EditorSessionIdRoute: EditorSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
