export const OPENAPI_DESCRIPTION = [
  "Megick for web and native app integrations.",
  "",
  "Authentication",
  "- Protected endpoints use the `mg_session` HTTP-only cookie, not a bearer token.",
  "- Browser clients must send credentials on every protected request.",
  "- Native apps and webviews must persist the `Set-Cookie` value and replay the cookie on later requests.",
  "",
  "Dates and time",
  "- All timestamps are ISO 8601 strings in UTC unless an endpoint explicitly says otherwise.",
  "",
  "Pagination",
  "- Common query params are `page`, `pageSize`, `skip`, `take`, and `limit`.",
  "- Paginated responses return `items`, `total`, `page`, `pageSize`, `pageCount`, `hasNextPage`, and `hasPreviousPage`.",
  "",
  "Redirect and HTML endpoints",
  "- OAuth entry and callback endpoints may respond with `302` redirects.",
  "- Some OAuth callback endpoints return HTML meant for popup or embedded webview completion.",
  "",
  "Binary endpoints",
  "- Binary download and proxy endpoints return raw bytes rather than JSON.",
].join("\n");
